# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LEDBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LEDBoard
	pod 'LeanCloudObjc'
	pod 'Masonry'

  target 'LEDBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LEDBoardUITests' do
    # Pods for testing
  end

end
